version: "3"

services:
    blufferoverflow:
        build: .
        restart: always
        ports:
            - "17027:1337"
        read_only: true

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.102.0/24
